// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/netapp/trident/storage_drivers/ovh/api (interfaces: OVHClient)
//
// Generated by this command:
//
//	mockgen -destination=../../../mocks/mock_storage_drivers/mock_ovh/mock_api.go github.com/netapp/trident/storage_drivers/ovh/api OVHClient
//

// Package mock_api is a generated GoMock package.
package mock_api

import (
	context "context"
	reflect "reflect"
	time "time"

	storage "github.com/netapp/trident/storage"
	api "github.com/netapp/trident/storage_drivers/ovh/api"
	gomock "go.uber.org/mock/gomock"
)

// MockOVHClient is a mock of OVHClient interface.
type MockOVHClient struct {
	ctrl     *gomock.Controller
	recorder *MockOVHClientMockRecorder
}

// MockOVHClientMockRecorder is the mock recorder for MockOVHClient.
type MockOVHClientMockRecorder struct {
	mock *MockOVHClient
}

// NewMockOVHClient creates a new mock instance.
func NewMockOVHClient(ctrl *gomock.Controller) *MockOVHClient {
	mock := &MockOVHClient{ctrl: ctrl}
	mock.recorder = &MockOVHClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOVHClient) EXPECT() *MockOVHClientMockRecorder {
	return m.recorder
}

// CapacityPoolsForStoragePool mocks base method.
func (m *MockOVHClient) CapacityPoolsForStoragePool(arg0 context.Context, arg1 storage.Pool, arg2 string) []*api.CapacityPool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CapacityPoolsForStoragePool", arg0, arg1, arg2)
	ret0, _ := ret[0].([]*api.CapacityPool)
	return ret0
}

// CapacityPoolsForStoragePool indicates an expected call of CapacityPoolsForStoragePool.
func (mr *MockOVHClientMockRecorder) CapacityPoolsForStoragePool(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CapacityPoolsForStoragePool", reflect.TypeOf((*MockOVHClient)(nil).CapacityPoolsForStoragePool), arg0, arg1, arg2)
}

// CapacityPoolsForStoragePools mocks base method.
func (m *MockOVHClient) CapacityPoolsForStoragePools(arg0 context.Context) []*api.CapacityPool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CapacityPoolsForStoragePools", arg0)
	ret0, _ := ret[0].([]*api.CapacityPool)
	return ret0
}

// CapacityPoolsForStoragePools indicates an expected call of CapacityPoolsForStoragePools.
func (mr *MockOVHClientMockRecorder) CapacityPoolsForStoragePools(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CapacityPoolsForStoragePools", reflect.TypeOf((*MockOVHClient)(nil).CapacityPoolsForStoragePools), arg0)
}

// CreateExportRule mocks base method.
func (m *MockOVHClient) CreateExportRule(arg0 context.Context, arg1 *api.Volume, arg2 *api.ExportRuleCreateRequest) (*api.ExportRule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateExportRule", arg0, arg1, arg2)
	ret0, _ := ret[0].(*api.ExportRule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateExportRule indicates an expected call of CreateExportRule.
func (mr *MockOVHClientMockRecorder) CreateExportRule(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateExportRule", reflect.TypeOf((*MockOVHClient)(nil).CreateExportRule), arg0, arg1, arg2)
}

// CreateSnapshot mocks base method.
func (m *MockOVHClient) CreateSnapshot(arg0 context.Context, arg1 *api.Volume, arg2 string) (*api.Snapshot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSnapshot", arg0, arg1, arg2)
	ret0, _ := ret[0].(*api.Snapshot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSnapshot indicates an expected call of CreateSnapshot.
func (mr *MockOVHClientMockRecorder) CreateSnapshot(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSnapshot", reflect.TypeOf((*MockOVHClient)(nil).CreateSnapshot), arg0, arg1, arg2)
}

// CreateVolume mocks base method.
func (m *MockOVHClient) CreateVolume(arg0 context.Context, arg1 *api.VolumeCreateRequest) (*api.Volume, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateVolume", arg0, arg1)
	ret0, _ := ret[0].(*api.Volume)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateVolume indicates an expected call of CreateVolume.
func (mr *MockOVHClientMockRecorder) CreateVolume(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateVolume", reflect.TypeOf((*MockOVHClient)(nil).CreateVolume), arg0, arg1)
}

// DeleteExportRule mocks base method.
func (m *MockOVHClient) DeleteExportRule(arg0 context.Context, arg1 *api.Volume, arg2 *api.ExportRule) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteExportRule", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteExportRule indicates an expected call of DeleteExportRule.
func (mr *MockOVHClientMockRecorder) DeleteExportRule(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteExportRule", reflect.TypeOf((*MockOVHClient)(nil).DeleteExportRule), arg0, arg1, arg2)
}

// DeleteSnapshot mocks base method.
func (m *MockOVHClient) DeleteSnapshot(arg0 context.Context, arg1 *api.Volume, arg2 *api.Snapshot) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSnapshot", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSnapshot indicates an expected call of DeleteSnapshot.
func (mr *MockOVHClientMockRecorder) DeleteSnapshot(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSnapshot", reflect.TypeOf((*MockOVHClient)(nil).DeleteSnapshot), arg0, arg1, arg2)
}

// DeleteVolume mocks base method.
func (m *MockOVHClient) DeleteVolume(arg0 context.Context, arg1 *api.Volume) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteVolume", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteVolume indicates an expected call of DeleteVolume.
func (mr *MockOVHClientMockRecorder) DeleteVolume(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteVolume", reflect.TypeOf((*MockOVHClient)(nil).DeleteVolume), arg0, arg1)
}

// EnsureVolumeInValidCapacityPool mocks base method.
func (m *MockOVHClient) EnsureVolumeInValidCapacityPool(arg0 context.Context, arg1 *api.Volume) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnsureVolumeInValidCapacityPool", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// EnsureVolumeInValidCapacityPool indicates an expected call of EnsureVolumeInValidCapacityPool.
func (mr *MockOVHClientMockRecorder) EnsureVolumeInValidCapacityPool(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnsureVolumeInValidCapacityPool", reflect.TypeOf((*MockOVHClient)(nil).EnsureVolumeInValidCapacityPool), arg0, arg1)
}

// ExportRuleByID mocks base method.
func (m *MockOVHClient) ExportRuleByID(arg0 context.Context, arg1 *api.Volume, arg2 string) (*api.ExportRule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExportRuleByID", arg0, arg1, arg2)
	ret0, _ := ret[0].(*api.ExportRule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExportRuleByID indicates an expected call of ExportRuleByID.
func (mr *MockOVHClientMockRecorder) ExportRuleByID(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExportRuleByID", reflect.TypeOf((*MockOVHClient)(nil).ExportRuleByID), arg0, arg1, arg2)
}

// ExportRulesExists mocks base method.
func (m *MockOVHClient) ExportRulesExists(arg0 context.Context, arg1 *api.Volume, arg2 string) (bool, []*api.ExportRule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExportRulesExists", arg0, arg1, arg2)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].([]*api.ExportRule)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ExportRulesExists indicates an expected call of ExportRulesExists.
func (mr *MockOVHClientMockRecorder) ExportRulesExists(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExportRulesExists", reflect.TypeOf((*MockOVHClient)(nil).ExportRulesExists), arg0, arg1, arg2)
}

// ExportRulesForVolume mocks base method.
func (m *MockOVHClient) ExportRulesForVolume(arg0 context.Context, arg1 *api.Volume) ([]*api.ExportRule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExportRulesForVolume", arg0, arg1)
	ret0, _ := ret[0].([]*api.ExportRule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExportRulesForVolume indicates an expected call of ExportRulesForVolume.
func (mr *MockOVHClientMockRecorder) ExportRulesForVolume(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExportRulesForVolume", reflect.TypeOf((*MockOVHClient)(nil).ExportRulesForVolume), arg0, arg1)
}

// Init mocks base method.
func (m *MockOVHClient) Init(arg0 context.Context, arg1 map[string]storage.Pool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Init", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Init indicates an expected call of Init.
func (mr *MockOVHClientMockRecorder) Init(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Init", reflect.TypeOf((*MockOVHClient)(nil).Init), arg0, arg1)
}

// RefreshOVHResources mocks base method.
func (m *MockOVHClient) RefreshOVHResources(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RefreshOVHResources", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// RefreshOVHResources indicates an expected call of RefreshOVHResources.
func (mr *MockOVHClientMockRecorder) RefreshOVHResources(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefreshOVHResources", reflect.TypeOf((*MockOVHClient)(nil).RefreshOVHResources), arg0)
}

// ResizeVolume mocks base method.
func (m *MockOVHClient) ResizeVolume(arg0 context.Context, arg1 *api.Volume, arg2 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResizeVolume", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// ResizeVolume indicates an expected call of ResizeVolume.
func (mr *MockOVHClientMockRecorder) ResizeVolume(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResizeVolume", reflect.TypeOf((*MockOVHClient)(nil).ResizeVolume), arg0, arg1, arg2)
}

// RestoreSnapshot mocks base method.
func (m *MockOVHClient) RestoreSnapshot(arg0 context.Context, arg1 *api.Volume, arg2 *api.Snapshot) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RestoreSnapshot", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// RestoreSnapshot indicates an expected call of RestoreSnapshot.
func (mr *MockOVHClientMockRecorder) RestoreSnapshot(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RestoreSnapshot", reflect.TypeOf((*MockOVHClient)(nil).RestoreSnapshot), arg0, arg1, arg2)
}

// SnapshotByID mocks base method.
func (m *MockOVHClient) SnapshotByID(arg0 context.Context, arg1 *api.Volume, arg2 string) (*api.Snapshot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SnapshotByID", arg0, arg1, arg2)
	ret0, _ := ret[0].(*api.Snapshot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SnapshotByID indicates an expected call of SnapshotByID.
func (mr *MockOVHClientMockRecorder) SnapshotByID(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SnapshotByID", reflect.TypeOf((*MockOVHClient)(nil).SnapshotByID), arg0, arg1, arg2)
}

// SnapshotForVolume mocks base method.
func (m *MockOVHClient) SnapshotForVolume(arg0 context.Context, arg1 *api.Volume, arg2 string) (*api.Snapshot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SnapshotForVolume", arg0, arg1, arg2)
	ret0, _ := ret[0].(*api.Snapshot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SnapshotForVolume indicates an expected call of SnapshotForVolume.
func (mr *MockOVHClientMockRecorder) SnapshotForVolume(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SnapshotForVolume", reflect.TypeOf((*MockOVHClient)(nil).SnapshotForVolume), arg0, arg1, arg2)
}

// SnapshotsForVolume mocks base method.
func (m *MockOVHClient) SnapshotsForVolume(arg0 context.Context, arg1 *api.Volume) (*[]*api.Snapshot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SnapshotsForVolume", arg0, arg1)
	ret0, _ := ret[0].(*[]*api.Snapshot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SnapshotsForVolume indicates an expected call of SnapshotsForVolume.
func (mr *MockOVHClientMockRecorder) SnapshotsForVolume(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SnapshotsForVolume", reflect.TypeOf((*MockOVHClient)(nil).SnapshotsForVolume), arg0, arg1)
}

// Volume mocks base method.
func (m *MockOVHClient) Volume(arg0 context.Context, arg1 *storage.VolumeConfig) (*api.Volume, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Volume", arg0, arg1)
	ret0, _ := ret[0].(*api.Volume)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Volume indicates an expected call of Volume.
func (mr *MockOVHClientMockRecorder) Volume(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Volume", reflect.TypeOf((*MockOVHClient)(nil).Volume), arg0, arg1)
}

// VolumeAccessPaths mocks base method.
func (m *MockOVHClient) VolumeAccessPaths(arg0 context.Context, arg1 *api.Volume) ([]*api.AccessPath, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VolumeAccessPaths", arg0, arg1)
	ret0, _ := ret[0].([]*api.AccessPath)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VolumeAccessPaths indicates an expected call of VolumeAccessPaths.
func (mr *MockOVHClientMockRecorder) VolumeAccessPaths(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VolumeAccessPaths", reflect.TypeOf((*MockOVHClient)(nil).VolumeAccessPaths), arg0, arg1)
}

// VolumeByID mocks base method.
func (m *MockOVHClient) VolumeByID(arg0 context.Context, arg1 string) (*api.Volume, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VolumeByID", arg0, arg1)
	ret0, _ := ret[0].(*api.Volume)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VolumeByID indicates an expected call of VolumeByID.
func (mr *MockOVHClientMockRecorder) VolumeByID(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VolumeByID", reflect.TypeOf((*MockOVHClient)(nil).VolumeByID), arg0, arg1)
}

// VolumeByMountPointName mocks base method.
func (m *MockOVHClient) VolumeByMountPointName(arg0 context.Context, arg1 string) (*api.Volume, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VolumeByMountPointName", arg0, arg1)
	ret0, _ := ret[0].(*api.Volume)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VolumeByMountPointName indicates an expected call of VolumeByMountPointName.
func (mr *MockOVHClientMockRecorder) VolumeByMountPointName(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VolumeByMountPointName", reflect.TypeOf((*MockOVHClient)(nil).VolumeByMountPointName), arg0, arg1)
}

// VolumeExists mocks base method.
func (m *MockOVHClient) VolumeExists(arg0 context.Context, arg1 *storage.VolumeConfig) (bool, *api.Volume, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VolumeExists", arg0, arg1)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(*api.Volume)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// VolumeExists indicates an expected call of VolumeExists.
func (mr *MockOVHClientMockRecorder) VolumeExists(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VolumeExists", reflect.TypeOf((*MockOVHClient)(nil).VolumeExists), arg0, arg1)
}

// VolumeExistsByID mocks base method.
func (m *MockOVHClient) VolumeExistsByID(arg0 context.Context, arg1 string) (bool, *api.Volume, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VolumeExistsByID", arg0, arg1)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(*api.Volume)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// VolumeExistsByID indicates an expected call of VolumeExistsByID.
func (mr *MockOVHClientMockRecorder) VolumeExistsByID(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VolumeExistsByID", reflect.TypeOf((*MockOVHClient)(nil).VolumeExistsByID), arg0, arg1)
}

// VolumeExistsByMountPointName mocks base method.
func (m *MockOVHClient) VolumeExistsByMountPointName(arg0 context.Context, arg1 string) (bool, *api.Volume, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VolumeExistsByMountPointName", arg0, arg1)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(*api.Volume)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// VolumeExistsByMountPointName indicates an expected call of VolumeExistsByMountPointName.
func (mr *MockOVHClientMockRecorder) VolumeExistsByMountPointName(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VolumeExistsByMountPointName", reflect.TypeOf((*MockOVHClient)(nil).VolumeExistsByMountPointName), arg0, arg1)
}

// Volumes mocks base method.
func (m *MockOVHClient) Volumes(arg0 context.Context) ([]*api.Volume, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Volumes", arg0)
	ret0, _ := ret[0].([]*api.Volume)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Volumes indicates an expected call of Volumes.
func (mr *MockOVHClientMockRecorder) Volumes(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Volumes", reflect.TypeOf((*MockOVHClient)(nil).Volumes), arg0)
}

// WaitForExportRuleStatus mocks base method.
func (m *MockOVHClient) WaitForExportRuleStatus(arg0 context.Context, arg1 *api.Volume, arg2 *api.ExportRule, arg3 string, arg4 []string, arg5 time.Duration) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WaitForExportRuleStatus", arg0, arg1, arg2, arg3, arg4, arg5)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// WaitForExportRuleStatus indicates an expected call of WaitForExportRuleStatus.
func (mr *MockOVHClientMockRecorder) WaitForExportRuleStatus(arg0, arg1, arg2, arg3, arg4, arg5 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WaitForExportRuleStatus", reflect.TypeOf((*MockOVHClient)(nil).WaitForExportRuleStatus), arg0, arg1, arg2, arg3, arg4, arg5)
}

// WaitForSnapshotStatus mocks base method.
func (m *MockOVHClient) WaitForSnapshotStatus(arg0 context.Context, arg1 *api.Volume, arg2 *api.Snapshot, arg3 string, arg4 []string, arg5 time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WaitForSnapshotStatus", arg0, arg1, arg2, arg3, arg4, arg5)
	ret0, _ := ret[0].(error)
	return ret0
}

// WaitForSnapshotStatus indicates an expected call of WaitForSnapshotStatus.
func (mr *MockOVHClientMockRecorder) WaitForSnapshotStatus(arg0, arg1, arg2, arg3, arg4, arg5 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WaitForSnapshotStatus", reflect.TypeOf((*MockOVHClient)(nil).WaitForSnapshotStatus), arg0, arg1, arg2, arg3, arg4, arg5)
}

// WaitForVolumeStatus mocks base method.
func (m *MockOVHClient) WaitForVolumeStatus(arg0 context.Context, arg1 *api.Volume, arg2 string, arg3 []string, arg4 time.Duration) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WaitForVolumeStatus", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// WaitForVolumeStatus indicates an expected call of WaitForVolumeStatus.
func (mr *MockOVHClientMockRecorder) WaitForVolumeStatus(arg0, arg1, arg2, arg3, arg4 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WaitForVolumeStatus", reflect.TypeOf((*MockOVHClient)(nil).WaitForVolumeStatus), arg0, arg1, arg2, arg3, arg4)
}
